### PR TITLE
Feat 156 vite + carbon 11 migration

### PR DESCRIPTION
**Pull request by timrbula**
## Context

Related Issues(s): #156 

Build Number: 3.12.12

## Checklist:

- [x] Verified in an integrated environment
- [x] Unit and integration tests passing
- [x] Semantic HTML with accessibility support
- [x] No linting, test console, or browser console errors (best effort)
- [x] JSDoc comment blocks for complex code

## PR Review Guidance

Well, check that _everything_ works :|

- Unit and integration tests are passing

## Additional Info

It's a big one

- Vite
- Carbon 11
- Latest addons lib

TODO
- Cleanup

### CODE REVIEW

**Review by LucasGrimauth — COMMENTED** [review]
Hey Tim, almost everything looks good! Some nitpicks I noticed:

1. The Execution "View Log" modal has its toggle clipped a bit.

image

2. The text and icons on these buttons seem to be too close.

image

**Review by Okisa — CHANGES_REQUESTED** [review]
Hey Tim! Looking good!
The only issue I saw is the drag and drop not working on the Task Manager / Team Tasks.

**Comment by timrbula** [comment]
> Hey Tim! Looking good! The only issue I saw is the drag and drop not working on the Task Manager / Team Tasks on Definition Fields.

Thanks, fixed

**Review by Okisa — DISMISSED** [review]
Looking good now!

**Review by LucasGrimauth — COMMENTED** [review]
Looks good Tim! Only thing I noticed now is that the "Follow log" toggle I mentioned before doesn't seem to be working. It doesn't change its state when I click on it.

**Review by Okisa — APPROVED** [review]
Tested in dev, all good!

**Review by LucasGrimauth — APPROVED** [review]
Looks good Tim!

**Pull request merged**
