### PR TITLE
feat [274, 324] User Detailed page and Team/User labels.

### PR DESCRIPTION
**Pull request by LucasGrimauth**
## Context

Related Issues(s): 
https://github.com/boomerang-io/roadmap/issues/274
https://github.com/boomerang-io/roadmap/issues/324

Build Number: 3.5.26

### CODE REVIEW

**Review by Okisa — CHANGES_REQUESTED** [review]
Hi Lucas! Changes are looking good!
Somethings I noticed, they apply for both Users and Teams:

- Table is not scrolling 
image

- When you try to access a workflow activity, it shows an error 404, but if you try to open on a new tab the link works. Tested in dev and locally.
flow_user01

**Review by Okisa — DISMISSED** [review]
Looking good now!

**Review by Okisa — APPROVED** [review]
Tested new Label section locally, looks good!

**Comment by timrbula** [comment]
LGTM. Nice work on this @LucasGrimauth

**Pull request merged**
